### ISSUE TITLE
Is it possible to default results to Wikiwand links?

### ISSUE THREAD

**Issue by nikivdev** [smallbrownbike/wikisearch#5]
[WIkiwand ](http://www.wikiwand.com/) has a lot better user experience.

**Comment by smallbrownbike** [comment]
Hey @nikitavoloboev! If you click the search icon on a results page now, you'll see an option to view results as Wikiwand links instead of Wikipedia links. Thanks for the feedback!

**Comment by nikivdev** [comment]
That's awesome. Thank you.

Can you please however allow users to set it as default?
